import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";

const withNextIntl = createNextIntlPlugin("./src/i18n.ts");

const nextConfig: NextConfig = {
  output: "standalone",
  experimental: {
    serverActions: {
      bodySizeLimit: "100mb",
    },
  },
  transpilePackages: [
    "@adobe/react-spectrum",
    "@react-spectrum/actionbar",
    "@react-spectrum/actiongroup",
    "@react-spectrum/actionmenu",
    "@react-spectrum/autocomplete",
    "@react-spectrum/avatar",
    "@react-spectrum/badge",
    "@react-spectrum/breadcrumbs",
    "@react-spectrum/button",
    "@react-spectrum/buttongroup",
    "@react-spectrum/calendar",
    "@react-spectrum/checkbox",
    "@react-spectrum/color",
    "@react-spectrum/combobox",
    "@react-spectrum/contextualhelp",
    "@react-spectrum/datepicker",
    "@react-spectrum/dialog",
    "@react-spectrum/divider",
    "@react-spectrum/dnd",
    "@react-spectrum/dropzone",
    "@react-spectrum/filetrigger",
    "@react-spectrum/form",
    "@react-spectrum/icon",
    "@react-spectrum/illustratedmessage",
    "@react-spectrum/image",
    "@react-spectrum/inlinealert",
    "@react-spectrum/label",
    "@react-spectrum/labeledvalue",
    "@react-spectrum/layout",
    "@react-spectrum/link",
    "@react-spectrum/list",
    "@react-spectrum/listbox",
    "@react-spectrum/menu",
    "@react-spectrum/meter",
    "@react-spectrum/numberfield",
    "@react-spectrum/overlays",
    "@react-spectrum/picker",
    "@react-spectrum/progress",
    "@react-spectrum/provider",
    "@react-spectrum/radio",
    "@react-spectrum/searchfield",
    "@react-spectrum/slider",
    "@react-spectrum/statuslight",
    "@react-spectrum/steplist",
    "@react-spectrum/switch",
    "@react-spectrum/table",
    "@react-spectrum/tabs",
    "@react-spectrum/tag",
    "@react-spectrum/text",
    "@react-spectrum/textfield",
    "@react-spectrum/theme-dark",
    "@react-spectrum/theme-default",
    "@react-spectrum/theme-express",
    "@react-spectrum/theme-light",
    "@react-spectrum/toast",
    "@react-spectrum/tooltip",
    "@react-spectrum/tree",
    "@react-spectrum/utils",
    "@react-spectrum/view",
    "@react-spectrum/well",
    "@spectrum-icons/workflow",
    "@spectrum-icons/illustrations",
  ],
};

export default withNextIntl(nextConfig);
